
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js"

import type { RegistryIndex } from "~/registry/schema"

export const Index: RegistryIndex = {

  "accordion": {
    name: "accordion",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/accordion")),
    files: [{
      path: "registry/ui/accordion.tsx",
      type: "ui",
      target: ""
    }],
  },
  "alert": {
    name: "alert",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/alert")),
    files: [{
      path: "registry/ui/alert.tsx",
      type: "ui",
      target: ""
    }],
  },
  "alert-dialog": {
    name: "alert-dialog",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/alert-dialog")),
    files: [{
      path: "registry/ui/alert-dialog.tsx",
      type: "ui",
      target: ""
    }],
  },
  "aspect-ratio": {
    name: "aspect-ratio",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/aspect-ratio")),
    files: [{
      path: "registry/ui/aspect-ratio.tsx",
      type: "ui",
      target: ""
    }],
  },
  "avatar": {
    name: "avatar",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/avatar")),
    files: [{
      path: "registry/ui/avatar.tsx",
      type: "ui",
      target: ""
    }],
  },
  "badge-delta": {
    name: "badge-delta",
    description: "",
    type: "ui",
    registryDependencies: ["badge"],
    component: lazy(() => import("~/registry/ui/badge-delta")),
    files: [{
      path: "registry/ui/badge-delta.tsx",
      type: "ui",
      target: ""
    }],
  },
  "badge": {
    name: "badge",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/badge")),
    files: [{
      path: "registry/ui/badge.tsx",
      type: "ui",
      target: ""
    }],
  },
  "bar-list": {
    name: "bar-list",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/bar-list")),
    files: [{
      path: "registry/ui/bar-list.tsx",
      type: "ui",
      target: ""
    }],
  },
  "breadcrumb": {
    name: "breadcrumb",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/breadcrumb")),
    files: [{
      path: "registry/ui/breadcrumb.tsx",
      type: "ui",
      target: ""
    }],
  },
  "button": {
    name: "button",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/button")),
    files: [{
      path: "registry/ui/button.tsx",
      type: "ui",
      target: ""
    }],
  },
  "callout": {
    name: "callout",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/callout")),
    files: [{
      path: "registry/ui/callout.tsx",
      type: "ui",
      target: ""
    }],
  },
  "card": {
    name: "card",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/card")),
    files: [{
      path: "registry/ui/card.tsx",
      type: "ui",
      target: ""
    }],
  },
  "carousel": {
    name: "carousel",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/carousel")),
    files: [{
      path: "registry/ui/carousel.tsx",
      type: "ui",
      target: ""
    }],
  },
  "charts": {
    name: "charts",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/charts")),
    files: [{
      path: "registry/ui/charts.tsx",
      type: "ui",
      target: ""
    }],
  },
  "checkbox": {
    name: "checkbox",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/checkbox")),
    files: [{
      path: "registry/ui/checkbox.tsx",
      type: "ui",
      target: ""
    }],
  },
  "combobox": {
    name: "combobox",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/combobox")),
    files: [{
      path: "registry/ui/combobox.tsx",
      type: "ui",
      target: ""
    }],
  },
  "command": {
    name: "command",
    description: "",
    type: "ui",
    registryDependencies: ["dialog"],
    component: lazy(() => import("~/registry/ui/command")),
    files: [{
      path: "registry/ui/command.tsx",
      type: "ui",
      target: ""
    }],
  },
  "context-menu": {
    name: "context-menu",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/context-menu")),
    files: [{
      path: "registry/ui/context-menu.tsx",
      type: "ui",
      target: ""
    }],
  },
  "collapsible": {
    name: "collapsible",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/collapsible")),
    files: [{
      path: "registry/ui/collapsible.tsx",
      type: "ui",
      target: ""
    }],
  },
  "date-picker": {
    name: "date-picker",
    description: "",
    type: "ui",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/ui/date-picker")),
    files: [{
      path: "registry/ui/date-picker.tsx",
      type: "ui",
      target: ""
    }],
  },
  "delta-bar": {
    name: "delta-bar",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/delta-bar")),
    files: [{
      path: "registry/ui/delta-bar.tsx",
      type: "ui",
      target: ""
    }],
  },
  "dialog": {
    name: "dialog",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/dialog")),
    files: [{
      path: "registry/ui/dialog.tsx",
      type: "ui",
      target: ""
    }],
  },
  "drawer": {
    name: "drawer",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/drawer")),
    files: [{
      path: "registry/ui/drawer.tsx",
      type: "ui",
      target: ""
    }],
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/dropdown-menu")),
    files: [{
      path: "registry/ui/dropdown-menu.tsx",
      type: "ui",
      target: ""
    }],
  },
  "flex": {
    name: "flex",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/flex")),
    files: [{
      path: "registry/ui/flex.tsx",
      type: "ui",
      target: ""
    }],
  },
  "grid": {
    name: "grid",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/grid")),
    files: [{
      path: "registry/ui/grid.tsx",
      type: "ui",
      target: ""
    }],
  },
  "hover-card": {
    name: "hover-card",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/hover-card")),
    files: [{
      path: "registry/ui/hover-card.tsx",
      type: "ui",
      target: ""
    }],
  },
  "label": {
    name: "label",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/label")),
    files: [{
      path: "registry/ui/label.tsx",
      type: "ui",
      target: ""
    }],
  },
  "menubar": {
    name: "menubar",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/menubar")),
    files: [{
      path: "registry/ui/menubar.tsx",
      type: "ui",
      target: ""
    }],
  },
  "navigation-menu": {
    name: "navigation-menu",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/navigation-menu")),
    files: [{
      path: "registry/ui/navigation-menu.tsx",
      type: "ui",
      target: ""
    }],
  },
  "number-field": {
    name: "number-field",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/number-field")),
    files: [{
      path: "registry/ui/number-field.tsx",
      type: "ui",
      target: ""
    }],
  },
  "otp-field": {
    name: "otp-field",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/otp-field")),
    files: [{
      path: "registry/ui/otp-field.tsx",
      type: "ui",
      target: ""
    }],
  },
  "pagination": {
    name: "pagination",
    description: "",
    type: "ui",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/ui/pagination")),
    files: [{
      path: "registry/ui/pagination.tsx",
      type: "ui",
      target: ""
    }],
  },
  "popover": {
    name: "popover",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/popover")),
    files: [{
      path: "registry/ui/popover.tsx",
      type: "ui",
      target: ""
    }],
  },
  "progress": {
    name: "progress",
    description: "",
    type: "ui",
    registryDependencies: ["label"],
    component: lazy(() => import("~/registry/ui/progress")),
    files: [{
      path: "registry/ui/progress.tsx",
      type: "ui",
      target: ""
    }],
  },
  "progress-circle": {
    name: "progress-circle",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/progress-circle")),
    files: [{
      path: "registry/ui/progress-circle.tsx",
      type: "ui",
      target: ""
    }],
  },
  "radio-group": {
    name: "radio-group",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/radio-group")),
    files: [{
      path: "registry/ui/radio-group.tsx",
      type: "ui",
      target: ""
    }],
  },
  "resizable": {
    name: "resizable",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/resizable")),
    files: [{
      path: "registry/ui/resizable.tsx",
      type: "ui",
      target: ""
    }],
  },
  "select": {
    name: "select",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/select")),
    files: [{
      path: "registry/ui/select.tsx",
      type: "ui",
      target: ""
    }],
  },
  "separator": {
    name: "separator",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/separator")),
    files: [{
      path: "registry/ui/separator.tsx",
      type: "ui",
      target: ""
    }],
  },
  "sheet": {
    name: "sheet",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/sheet")),
    files: [{
      path: "registry/ui/sheet.tsx",
      type: "ui",
      target: ""
    }],
  },
  "sidebar": {
    name: "sidebar",
    description: "",
    type: "ui",
    registryDependencies: ["button","seperator","sheet","skeleton","text-field","tooltip","use-mobile"],
    component: lazy(() => import("~/registry/ui/sidebar")),
    files: [{
      path: "registry/ui/sidebar.tsx",
      type: "ui",
      target: ""
    }],
  },
  "skeleton": {
    name: "skeleton",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/skeleton")),
    files: [{
      path: "registry/ui/skeleton.tsx",
      type: "ui",
      target: ""
    }],
  },
  "slider": {
    name: "slider",
    description: "",
    type: "ui",
    registryDependencies: ["label"],
    component: lazy(() => import("~/registry/ui/slider")),
    files: [{
      path: "registry/ui/slider.tsx",
      type: "ui",
      target: ""
    }],
  },
  "sonner": {
    name: "sonner",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/sonner")),
    files: [{
      path: "registry/ui/sonner.tsx",
      type: "ui",
      target: ""
    }],
  },
  "switch": {
    name: "switch",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/switch")),
    files: [{
      path: "registry/ui/switch.tsx",
      type: "ui",
      target: ""
    }],
  },
  "table": {
    name: "table",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/table")),
    files: [{
      path: "registry/ui/table.tsx",
      type: "ui",
      target: ""
    }],
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/tabs")),
    files: [{
      path: "registry/ui/tabs.tsx",
      type: "ui",
      target: ""
    }],
  },
  "text-field": {
    name: "text-field",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/text-field")),
    files: [{
      path: "registry/ui/text-field.tsx",
      type: "ui",
      target: ""
    }],
  },
  "timeline": {
    name: "timeline",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/timeline")),
    files: [{
      path: "registry/ui/timeline.tsx",
      type: "ui",
      target: ""
    }],
  },
  "toast": {
    name: "toast",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/toast")),
    files: [{
      path: "registry/ui/toast.tsx",
      type: "ui",
      target: ""
    }],
  },
  "toggle": {
    name: "toggle",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/toggle")),
    files: [{
      path: "registry/ui/toggle.tsx",
      type: "ui",
      target: ""
    }],
  },
  "toggle-group": {
    name: "toggle-group",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/toggle-group")),
    files: [{
      path: "registry/ui/toggle-group.tsx",
      type: "ui",
      target: ""
    }],
  },
  "tooltip": {
    name: "tooltip",
    description: "",
    type: "ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/tooltip")),
    files: [{
      path: "registry/ui/tooltip.tsx",
      type: "ui",
      target: ""
    }],
  },
  "accordion-demo": {
    name: "accordion-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/accordion-demo")),
    files: [{
      path: "registry/example/accordion-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "alert-demo": {
    name: "alert-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/alert-demo")),
    files: [{
      path: "registry/example/alert-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "alert-dialog-demo": {
    name: "alert-dialog-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/alert-dialog-demo")),
    files: [{
      path: "registry/example/alert-dialog-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "aspect-ratio-demo": {
    name: "aspect-ratio-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/aspect-ratio-demo")),
    files: [{
      path: "registry/example/aspect-ratio-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "avatar-demo": {
    name: "avatar-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/avatar-demo")),
    files: [{
      path: "registry/example/avatar-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "button-demo": {
    name: "button-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/button-demo")),
    files: [{
      path: "registry/example/button-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "badge-demo": {
    name: "badge-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/badge-demo")),
    files: [{
      path: "registry/example/badge-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "badge-delta-demo": {
    name: "badge-delta-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/badge-delta-demo")),
    files: [{
      path: "registry/example/badge-delta-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "bar-list-demo": {
    name: "bar-list-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/bar-list-demo")),
    files: [{
      path: "registry/example/bar-list-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "breadcrumb-demo": {
    name: "breadcrumb-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/breadcrumb-demo")),
    files: [{
      path: "registry/example/breadcrumb-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "calendar-demo": {
    name: "calendar-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/calendar-demo")),
    files: [{
      path: "registry/example/calendar-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "callout-demo": {
    name: "callout-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/callout-demo")),
    files: [{
      path: "registry/example/callout-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "card-demo": {
    name: "card-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/card-demo")),
    files: [{
      path: "registry/example/card-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "carousel-demo": {
    name: "carousel-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/carousel-demo")),
    files: [{
      path: "registry/example/carousel-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "carousel-size-demo": {
    name: "carousel-size-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/carousel-size-demo")),
    files: [{
      path: "registry/example/carousel-size-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "carousel-api-demo": {
    name: "carousel-api-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/carousel-api-demo")),
    files: [{
      path: "registry/example/carousel-api-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "carousel-orientation-demo": {
    name: "carousel-orientation-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/carousel-orientation-demo")),
    files: [{
      path: "registry/example/carousel-orientation-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "carousel-plugin-demo": {
    name: "carousel-plugin-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/carousel-plugin-demo")),
    files: [{
      path: "registry/example/carousel-plugin-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "carousel-spacing-demo": {
    name: "carousel-spacing-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/carousel-spacing-demo")),
    files: [{
      path: "registry/example/carousel-spacing-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "area-chart-demo": {
    name: "area-chart-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/area-chart-demo")),
    files: [{
      path: "registry/example/area-chart-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "pie-chart-demo": {
    name: "pie-chart-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/pie-chart-demo")),
    files: [{
      path: "registry/example/pie-chart-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "bar-chart-demo": {
    name: "bar-chart-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/bar-chart-demo")),
    files: [{
      path: "registry/example/bar-chart-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/checkbox-demo")),
    files: [{
      path: "registry/example/checkbox-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "checkbox-indeterminate-demo": {
    name: "checkbox-indeterminate-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/checkbox-indeterminate-demo")),
    files: [{
      path: "registry/example/checkbox-indeterminate-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "collapsible-demo": {
    name: "collapsible-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/collapsible-demo")),
    files: [{
      path: "registry/example/collapsible-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "combobox-demo": {
    name: "combobox-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/combobox-demo")),
    files: [{
      path: "registry/example/combobox-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "command-demo": {
    name: "command-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/command-demo")),
    files: [{
      path: "registry/example/command-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "command-dialog-demo": {
    name: "command-dialog-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/command-dialog-demo")),
    files: [{
      path: "registry/example/command-dialog-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "context-menu-demo": {
    name: "context-menu-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/context-menu-demo")),
    files: [{
      path: "registry/example/context-menu-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "data-table-demo": {
    name: "data-table-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/data-table-demo")),
    files: [{
      path: "registry/example/data-table-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "date-picker-demo": {
    name: "date-picker-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/date-picker-demo")),
    files: [{
      path: "registry/example/date-picker-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "date-range-demo": {
    name: "date-range-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/date-range-demo")),
    files: [{
      path: "registry/example/date-range-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "delta-bar-demo": {
    name: "delta-bar-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/delta-bar-demo")),
    files: [{
      path: "registry/example/delta-bar-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "dialog-demo": {
    name: "dialog-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/dialog-demo")),
    files: [{
      path: "registry/example/dialog-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "drawer-demo": {
    name: "drawer-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/drawer-demo")),
    files: [{
      path: "registry/example/drawer-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "drawer-dialog": {
    name: "drawer-dialog",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/drawer-dialog")),
    files: [{
      path: "registry/example/drawer-dialog.tsx",
      type: "example",
      target: ""
    }],
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/dropdown-menu-demo")),
    files: [{
      path: "registry/example/dropdown-menu-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "flex-demo": {
    name: "flex-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/flex-demo")),
    files: [{
      path: "registry/example/flex-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "grid-demo": {
    name: "grid-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/grid-demo")),
    files: [{
      path: "registry/example/grid-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "hover-card-demo": {
    name: "hover-card-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/hover-card-demo")),
    files: [{
      path: "registry/example/hover-card-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "menubar-demo": {
    name: "menubar-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/menubar-demo")),
    files: [{
      path: "registry/example/menubar-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "mode-toggle": {
    name: "mode-toggle",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/mode-toggle")),
    files: [{
      path: "registry/example/mode-toggle.tsx",
      type: "example",
      target: ""
    }],
  },
  "navigation-menu-demo": {
    name: "navigation-menu-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/navigation-menu-demo")),
    files: [{
      path: "registry/example/navigation-menu-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "number-field-demo": {
    name: "number-field-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/number-field-demo")),
    files: [{
      path: "registry/example/number-field-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "otp-field-demo": {
    name: "otp-field-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/otp-field-demo")),
    files: [{
      path: "registry/example/otp-field-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "pagination-demo": {
    name: "pagination-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/pagination-demo")),
    files: [{
      path: "registry/example/pagination-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "popover-demo": {
    name: "popover-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/popover-demo")),
    files: [{
      path: "registry/example/popover-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "progress-demo": {
    name: "progress-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/progress-demo")),
    files: [{
      path: "registry/example/progress-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "progress-circle-demo": {
    name: "progress-circle-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/progress-circle-demo")),
    files: [{
      path: "registry/example/progress-circle-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "radio-group-demo": {
    name: "radio-group-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/radio-group-demo")),
    files: [{
      path: "registry/example/radio-group-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "resizable-demo": {
    name: "resizable-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/resizable-demo")),
    files: [{
      path: "registry/example/resizable-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "select-demo": {
    name: "select-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/select-demo")),
    files: [{
      path: "registry/example/select-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "separator-demo": {
    name: "separator-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/separator-demo")),
    files: [{
      path: "registry/example/separator-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "sheet-demo": {
    name: "sheet-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/sheet-demo")),
    files: [{
      path: "registry/example/sheet-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "skeleton-demo": {
    name: "skeleton-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/skeleton-demo")),
    files: [{
      path: "registry/example/skeleton-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "slider-demo": {
    name: "slider-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/slider-demo")),
    files: [{
      path: "registry/example/slider-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "sonner-demo": {
    name: "sonner-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/sonner-demo")),
    files: [{
      path: "registry/example/sonner-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "switch-demo": {
    name: "switch-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/switch-demo")),
    files: [{
      path: "registry/example/switch-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "table-demo": {
    name: "table-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/table-demo")),
    files: [{
      path: "registry/example/table-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "tabs-demo": {
    name: "tabs-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/tabs-demo")),
    files: [{
      path: "registry/example/tabs-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "text-field-demo": {
    name: "text-field-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/text-field-demo")),
    files: [{
      path: "registry/example/text-field-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "text-field-error-demo": {
    name: "text-field-error-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/text-field-error-demo")),
    files: [{
      path: "registry/example/text-field-error-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "text-field-textarea-demo": {
    name: "text-field-textarea-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/text-field-textarea-demo")),
    files: [{
      path: "registry/example/text-field-textarea-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "timeline-demo": {
    name: "timeline-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/timeline-demo")),
    files: [{
      path: "registry/example/timeline-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "toast-demo": {
    name: "toast-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/toast-demo")),
    files: [{
      path: "registry/example/toast-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "toggle-demo": {
    name: "toggle-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/toggle-demo")),
    files: [{
      path: "registry/example/toggle-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "toggle-group-demo": {
    name: "toggle-group-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/toggle-group-demo")),
    files: [{
      path: "registry/example/toggle-group-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "tooltip-demo": {
    name: "tooltip-demo",
    description: "",
    type: "example",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/example/tooltip-demo")),
    files: [{
      path: "registry/example/tooltip-demo.tsx",
      type: "example",
      target: ""
    }],
  },
  "sidebar-01": {
    name: "sidebar-01",
    description: "A simple sidebar with navigation grouped by section",
    type: "block",
    registryDependencies: ["sidebar","breadcrumb","separator","label","dropdown-menu"],
    component: lazy(() => import("~/registry/block/sidebar-01")),
    files: [{
      path: "registry/block/sidebar-01/index.tsx",
      type: "page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/block/sidebar-01/components/app-sidebar.tsx",
      type: "component",
      target: ""
    },{
      path: "registry/block/sidebar-01/components/search-form.tsx",
      type: "component",
      target: ""
    },{
      path: "registry/block/sidebar-01/components/version-switcher.tsx",
      type: "component",
      target: ""
    }],
  },
  "demo-sidebar": {
    name: "demo-sidebar",
    description: "",
    type: "block",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/block/demo-sidebar")),
    files: [{
      path: "registry/block/demo-sidebar.tsx",
      type: "component",
      target: ""
    }],
  },
}
